server:
  servlet:
    application-display-name: taotao-order-application
  port: 8093

spring:
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  scan:
    base-packages: com.suny.taotao.order
  application:
    name: taotao-order-application
embedded:
  zookeeper:
    port: 2181

# 购物车在cookie中保存的key
CART_KEY: TT_CART
# token在cookie中保存的值
TT_TOKEN: TT_TOKEN
# sso系统的url
SSO_URL: http://localhost:8090