server:
  servlet:
    application-display-name: taotao-content-provider

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf-8
  redis:
    timeout: 5000
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: com/suny/taotao/**/mapper/**/*.xml
  type-aliases-package: com.suny.taotao
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  scan:
    base-packages: com.suny.taotao.content.service.impl.content.service
embedded:
  zookeeper:
    port: 2181


INDEX_CONTENT: INDEX_CONTENT