server:
  servlet:
    application-display-name: taotao-item-application
  port: 8088

spring:
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**

dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  scan:
    base-packages: com.suny.taotao.item
  application:
    name: taotao-item-application
embedded:
  zookeeper:
    port: 2181


# 静态页面输出路径
HTML_OUT_PATH: /home/sunjianrong/IdeaProjects/shoppingMall/taotaoItemWeb/src/main/resources/out