server:
  servlet:
    application-display-name: taotao-cart-application
  port: 8001

spring:
   mvc:
    view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp

dubbo:
  metadata-report:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${dubbo.application.name}/dubbo.cache
  scan:
    base-packages: com.suny.taotao
  application:
    name: taotao-cart-application
embedded:
  zookeeper:
    port: 2181

# 购物车在cookie中保存的key
CART_KEY: TT_CART
  # 购物车有效期,默认为7天
CART_EXPIRE: 604800