server:
  servlet:
    application-display-name: taotao-manager-provider

spring:
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: FoNjfRQFtijmjpEI
      url: jdbc:mysql://localhost:3307/taotao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
  redis:
    timeout: 5000
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: com/suny/taotao/**/mapper/**/*.xml
  type-aliases-package: com.suny.taotao
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true


dubbo:
  metadata-report:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${dubbo.application.name}/dubbo.cache
  scan:
    base-packages: com.suny.taotao.manager
  application:
    name: taotao-manager-provider
embedded:
  zookeeper:
    port: 2181


#商品数据在reids中缓存的前缀
ITEM_INFO: ITEM_INFO
#商品数据缓存的过期时间，默认为一天
TIME_EXPIRE: 86400


